### ISSUE TITLE
How to fix author and update missing errors on Search Console Report ?

### ISSUE THREAD

**Issue by Frank0302** [godaddy/wp-primer-theme#133]
Help me, please.
My Google Search Console Report is like this:
[http://i1282.photobucket.com/albums/a536/Hatha_Yogi/Error_zpsjbxwr1xc.jpg](http://i1282.photobucket.com/albums/a536/Hatha_Yogi/Error_zpsjbxwr1xc.jpg)
I search this error on Google but I can't find the correct solution. It looks like the Primer theme is coded in unfamiliar way.
Thank you.

**Comment by frankiejarrett** [comment]
As to not depend on a 3rd party link for the graphic:

![error_zpsjbxwr1xc](https://cloud.githubusercontent.com/assets/522158/20902658/af430b0c-bafd-11e6-828e-69ed1b3ddf3a.jpg)

**Comment by frankiejarrett** [comment]
I don't know why there is an error for `Missing: author` since we do make use of `rel="author"` inside the `single.php` template.

I think we're going to need more information to get to the bottom of this one. If there are more specific errors you can drill down to and share, and even find which theme templates are in question, that would be very helpful.

Otherwise, we'll spin up a test site and see if we can replicate any of these, but that might take a while.

cf. http://microformats.org/wiki/rel-author
