### ISSUE TITLE
Few things

### ISSUE THREAD

**Issue by glados1337** [godaddy/wp-primer-theme#135]
Hi,

Your theme looks like nice, but i think theme need for some things if its possible to do ;).

1) Replace icons "post"
    a) Comment icon replace with:  http://fontawesome.io/icon/comment-o/
    b) User icon replace with: http://fontawesome.io/icon/user-o/

2) Header: 2400x1300 recommends, hmm nope, actually looking bad.
 On test site: http://evolvegame.funsite.cz/ 1920x610 and look croped, when i change site-header width / height it's still working but no responzive.

3) When i click on post i see before post "POST" useless on post, on page is ok.

4 Comment section looks like.. i trying in custom child via:
```
 .comment-list li.bypostauthor {

border-left: 3px solid #5a6175;
border-color: #fff;
border-radius: 0px!important;
}
```
Too much "importants" and dont work

5) In Child theme color changer not working.

Thank you ;) #

**Comment by glados1337** [comment]
2, 3 fixed

**Comment by glados1337** [comment]
Nobody know how to fix comments ? :(

**Comment by EvanHerman** [comment]
Hi @glados1337,

The border color of the comments are styled via the customizer and are styled using the 'Link Text' color picker.

The styles for this section are added inline to override the default styles set by the theme styles.css. The border is also only added to the comments made by the post author (`li.bypostauthor`).

Due to this limitation, the best way to override the color set by the color picker is to filter the color scheme using the `primer_colors` filter.

An example to set the comment border color via the `primer_colors` filter would look something like the following:

```php
function set_primer_border_color( $colors ) {
   
   $overrides = array(
        'link_color' => array(
            'rgba_css' => array(
                '.comment-list li.bypostauthor' => array(
                    'border-color' => '#fff',
                ),
            ),
        ),
    );

    return primer_array_replace_recursive( $colors, $overrides );

}
add_filter( 'primer_colors', 'set_primer_border_color' );
```

Thanks,
Evan

**Comment by glados1337** [comment]
Oh php solution.. in what php file i can write your code?

**Comment by EvanHerman** [comment]
Hi @glados1337,

That bit of code should go into your child theme **functions.php** file.

Evan

**Comment by glados1337** [comment]
Still working, comments borders is out, but cant set border-left at autor comments, your code mean delete all corders in comments, but still better then original borders. Thanks for a reply ;)
