### ISSUE TITLE
secondary sidebar

### ISSUE THREAD

**Issue by RandyStepanek** [godaddy/wp-primer-theme#197]
I'm using primer in two separate locations. One is at GoDaddy, and the other is at work on an IIS server.

In both locations, the secondary sidebar content simply will not display.

I have selected a 3 column layout:
![image](https://cloud.githubusercontent.com/assets/27784693/25199907/63dfd00a-251a-11e7-9543-fd2940e0cc2f.png)

and added content to secondary sidebar:
![image](https://cloud.githubusercontent.com/assets/27784693/25199962/9bcbdb94-251a-11e7-85be-1fdabaf38baf.png)

I've tested on the temporary site that is hosted at godaddy with the same results.

![image](https://cloud.githubusercontent.com/assets/27784693/25200316/e9cc1588-251b-11e7-9aac-502093afdcc9.png)

**Comment by EvanHerman** [comment]
Hi @RandyStepanek,

I just did a quick test and it does look like there is a bug occurring that is preventing the sidebar from appearing.

Let me take a deeper dive into it and see what I can come up with for a solution. We will most likely need to patch up this issue in the next release.

**Comment by EvanHerman** [comment]
After some additional testing it looks as though `primer_get_layout()` is returning empty inside of [sidebar-tertiary.php](https://github.com/godaddy/wp-primer-theme/blob/5d4070b8087469dc19057731b463b29f37763379/sidebar-tertiary.php#L11).

I will continue to do some digging and see what's going on.

**Comment by EvanHerman** [comment]
Hi @RandyStepanek 

After some further testing it looks like the issue is with `0 === strpos( primer_get_layout(), 'three-column-' )` inside of [sidebar-tertiary.php](https://github.com/godaddy/wp-primer-theme/blob/5d4070b8087469dc19057731b463b29f37763379/sidebar-tertiary.php#L11).

That line is checking if the current template contains the string 'three-column' at all. The line should read `is_bool( strpos( primer_get_layout(), 'three-column' ) )`, since `strpos` returns an integer (position of found string) when found or `FALSE` boolean value if not found.

This is going to get patched up and included in the next release of primer.

**Comment by RandyStepanek** [comment]
@EvanHerman Thank you. Primer is an excellent theme btw. My favorite.

**Comment by chaudharisuresh997** [comment]
updated theme but issue persist ;( at least can u paste ur all code of  sidebar-tertiary.php i will only replace the file sinsce i am not aware about wordpress php

**Comment by frankiejarrett** [comment]
@chaudharisuresh997 The fix for this was merged into `develop` yesterday. It is not in the `master` branch or part of any official release just yet. It will go out in the next one (1.7.1).

**Comment by chaudharisuresh997** [comment]
@fjarrett when you guys are releasing it in official release.
If i want to use code in develop can you please educate me on this.

**Comment by frankiejarrett** [comment]
@chaudharisuresh997 It will most likely be next week. 

We don't really have any guide handy for how to setup using `develop`. I suppose you can just [download the entire branch](https://github.com/godaddy/wp-primer-theme/archive/develop.zip), just keep in mind it has all the development files in it and we don't recommend doing this in production because it's not an official/stable release.
