### ISSUE TITLE
WooCommerce shop page does not inherit selected Primer page template

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#251]
On the shop page - changing the Primer page template does not appear to reflect any changes on front of site.

**Comment by 3D-DIYde** [comment]
Hi @EvanHerman 

any chances of getting this fixed in an upcoming release or any known workarounds? I'm using the Primer theme in my Blog for almost a year now and I'm very happy with it. But currently I'm setting up a Woocommerce Shop and it's quite annoying to be stuck with the narrow two-column layout for the shop.
I know there is a way to change defaults, which somehow works. But that would mean, I would have to change the layout for every existing und upcoming page and post, except for the shop.

**Comment by MariaManiccia** [comment]
Hello @EvanHerman and @3D-DIYde !

Were there any solutions for this bug? I am currently using this theme and a client would like to add the sidebar to the page, but I cannot add any widgets to that area and I cannot override the woocommerce theme template. Any suggestions?

**Comment by EvanHerman** [comment]
WooCommerce changed up it's templating system and they now load an archive template.

Have you tried creating a custom template?
https://docs.woocommerce.com/document/template-structure/

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
