### ISSUE TITLE
Improve UX for secondary sidebars

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-primer-theme#36]
The purpose of the secondary sidebar might be confusing for the users as the default layout doesn't show it. 

One way to improve this might be to add a small description on the secondary sidebar explaining when those widgets show up.

**Comment by frankiejarrett** [comment]
@jonathanbardo Looks like there is already a little explanation in the UI for this. Are you thinking of maybe making the message more prominent if you don't have a three-column layout selected?

<img width="297" alt="screen shot 2016-07-28 at 4 06 42 pm" src="https://cloud.githubusercontent.com/assets/522158/17229480/4d403d02-54dd-11e6-9bc6-ef84d0c6c495.png">
<img width="316" alt="screen shot 2016-07-28 at 4 06 29 pm" src="https://cloud.githubusercontent.com/assets/522158/17229481/4d5ad112-54dd-11e6-9b74-41e299e37371.png">

**Comment by jonathanbardo** [comment]
@fjarrett Actually I don't we didn't have a message. This is fine with me we can close this.

**Comment by samonja** [comment]
How do I change the default post/page layout to full width. Thanks

**Comment by frankiejarrett** [comment]
Hi @samonja - You can use the `primer_default_layout` filter [defined here](https://github.com/godaddy/wp-primer-theme/blob/5d4070b8087469dc19057731b463b29f37763379/inc/customizer/layouts.php#L76), and just return the key of any available layout [listed here](https://github.com/godaddy/wp-primer-theme/blob/5d4070b8087469dc19057731b463b29f37763379/inc/customizer/layouts.php#L51-L60).

```php
add_filter( 'primer_default_layout', function () {

	return 'one-column-wide';

} );
```

**Comment by samonja** [comment]
Is this how it suppose to look ... because I did that and nothing happen

/**
* Filter the default layout.
*
* @since 1.0.0
*
* @var string
*/
$default       = (string) apply_filters( 'primer_default_layout', $this->default );
$this->default = $this->layout_exists( $default ) ? $default : ( $this->layout_exists( $this->default ) ? $this->default : key( $this->layouts ) );

        add_filter( 'primer_default_layout', function () {

return 'one-column-wide';

} );

/**
* Filter if post/page overrides via meta box should be enabled.
*
* @since 1.0.0
*
* @var bool
*/



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by frankiejarrett** [comment]
Hey @samonja - you never want to modify theme files directly, they will be wiped out each time the theme receives an update. Filters should be added to your own [child theme](https://codex.wordpress.org/Child_Themes) or a [must-use plugin](https://codex.wordpress.org/Must_Use_Plugins).

If filters are new to you, [this is a good article](http://dev.themeblvd.com/tutorial/filters/) to learn about how they work.

Thanks for using Primer!

**Comment by samonja** [comment]
I know that. I have a child team. I want to know where to access the <wp_header> file.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by frankiejarrett** [comment]
@samonja In your example it appears you are editing the theme directly, and that's part of the reason why it's not working :-)

The `add_filter` must always be called _before_ it's defined with `apply_filters`, hence the reason for it to be done in a child theme or must-use plugin because they are loaded before parent themes.

Not sure what you mean about the header file.
