### ISSUE TITLE
Keep grandchild menu flyouts inside the viewable area

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#40]
If you have a really long Primary Menu with the last item containing children and grandchildren, it's possible for the grandchild flyout menu to be cutoff and overflow outside of the viewable area.

We should add logic to `navigation.js` to ensure the flyout will appear on the opposite side when it's too close to the browser window's edge.

<img width="427" alt="screen shot 2016-07-28 at 3 46 44 pm" src="https://cloud.githubusercontent.com/assets/522158/17229105/b99eccfe-54db-11e6-8a72-4814758a9dd5.png">

**Comment by tobeycodes** [comment]
When I was developing Ascension I rewrote Navigation.js with jQuery and solved this problem in the child theme only but I have just removed the navigation.js in Ascension since we recently rewrote it in Primer that solved the original problems. It's one less file to manage in the child theme but it means this problem is back in Ascension until we fix it in Primer for all child themes. 

We can at least use it as inspiration to solve the problem here
https://github.com/LiftUX/ascension-theme/blob/develop/assets/js/navigation.js

**Comment by frankiejarrett** [comment]
Here is a permalink to the script mentioned above: https://github.com/godaddy/wp-ascension-theme/blob/0937969925e22883635e06e8edc9db6006e29f92/assets/js/navigation.js#L21-L39
