### ISSUE TITLE
CSS output with default

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#48]
I think we can make the assumption that if we are using the default font and color scheme it is already being defined in the style.css so we do not need to output it.

Do you agree?

**Comment by frankiejarrett** [comment]
@schrapel I purposely removed this behavior for the following reasons:
1. It wasn't future-proof. Always outputting the custom CSS gives us the option to change the default colors in a theme update down the road without affecting existing users of that theme. It will be a poor experience if update their theme and the front-end colors change without warning. This way whatever they have their swatches saved as in the Customizer will always be what is displayed on their site.
2. It prevents people from filtering defaults because there the `style.css` will not match. For example, if a user wants to change the default color in their child theme (for whatever reason) they can simply filter the `primer_colors` array. However if the color is not also manually updated in the `style.css` file, the default would not display correctly.
