### ISSUE TITLE
Implement AMP template and style

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-primer-theme#77]
The AMP format seems to be constantly gaining traction and it would be interesting to offer it as part of the parent theme.

**Comment by frankiejarrett** [comment]
@jbardo Perhaps integrating with this plugin from Automattic: https://wordpress.org/plugins/amp/

**Comment by rajanvijayan** [comment]
@jonathanbardo and @fjarrett may I try to do this task? Do you have any contributor guidelines?

**Comment by westonruter** [comment]
I suggest adding `amp` theme support so that the theme's templates and styles can be used as is. Here's what the theme looks like side-by-side non-AMP and AMP in [1.2-beta2](https://github.com/ampproject/amp-wp/releases/tag/1.2-beta2) of the [official AMP plugin](https://wordpress.org/plugins/amp/) (which originated by Automattic):

![image](https://user-images.githubusercontent.com/134745/59382502-bc531500-8d12-11e9-9bd8-51fa58fcc6a1.png)

The main thing that doesn't work is the navigation, but that should be easily fixed by following the tutorial here: https://amp-wp.org/documentation/playbooks/toggling-hamburger-menus/

**Comment by westonruter** [comment]
@fjarrett I've gotten it most of the way in #288. As I hoped, this theme is proving very straightforward to make fully AMP-compatible.

**Comment by westonruter** [comment]
I've checked the Primer child themes for their AMP compatibility after #288 being merged, and there are a few issues:

Child theme | Issue  | Status
------------ | -------- | ---------
lyrical | There are broken paths to the Genericons font file in Primer which is causing an `excessive_css` AMP validation error. | PR with fix: https://github.com/godaddy/wp-lyrical-theme/pull/64
ascension | Same issue as above. | PR with fix: https://github.com/godaddy/wp-ascension-theme/pull/109
mins | A `search-nav.js` script is being enqueued which is causing an `invalid_element` AMP validation error. | Removal of dead script code and fixed Genericons in https://github.com/godaddy/wp-mins-theme/pull/66
stout | A `stout-hero.js` script is being enqueued which is causing an `invalid_element` AMP validation error. | See WIP PR at https://github.com/godaddy/wp-stout-theme/pull/58

Note: Every child theme appears to need the Genericons fix in https://github.com/godaddy/wp-lyrical-theme/pull/64.
